### ISSUE TITLE
[Discussion] Avoid truncating all tables when launching test suite

### ISSUE THREAD

**Issue by liqueurdetoile** [vierge-noire/cakephp-test-suite-light#14]
Hi,

At very beginning of each test, the fixture injector requests the truncation of all dirty tables and that the expected behavior. To do this, it uses the sniffer. Therefore, the fixture manager starts a new sniffer.

I'm using the `MysqlTriggerBasedTableSniffer`. At start, it :
- creates the temporary dirty table collector
- creates all triggers on regular tables to feed the collector when inserted
- creates the procedure to clean collected dirty tables
- **marks ALL tables as dirty and run the procedure**

The final step is at some time cost. About 15s in my 25 tables local dev setup. Not really a matter when running all tests but it becomes more painful when willing to run a single test multiple times while in active dev. For a 5s tests, I have to wait 20s to have it completed. In practice, I'm even temporally disabling listener by editing PHPUnit config if no fixtures/cleaning are required in the test.

As I understand it, emptying all databases at the very beginning is required to get rid of previous tests data remnants as truncation is done at test start and may even be skipped with the dedicated trait.

Instead of doing this, a final call to `FixtureManager::truncateDirtyTables` in the `endTestSuite` hook of the fixtures injector should achieve the same purpose and won't overload by 15s the test duration as by now. What do you think about it ?

**Comment by pabloelcolombiano** [comment]
I am surprised that the truncation of all tables take so much time for so few tables. I have made a performance test on 100 tables, and the initial truncation takes around 1s.

One advantage of cleaning the test DB before and not after, is that it enables the developer to read the state in which the database is left after the last test was performed. I therefore would rather think of a solution to speed-up the initial truncation.

I am wondering how...

**Comment by pabloelcolombiano** [comment]
What you could do is to use a non-temporary dirty table collector.

In `bootstrap.php`, you may call: `CakephpTestSuiteLight\Sniffer\SnifferRegistry::get('test')->activateMainMode();`, assuming that your test commection is named `test`.

This way, you can comment out the line 76 `$this->cleanAllTables();` in the MysqlTriggerBasedTableSniffer.php, since the dirty table locator now is not temporary anymore.

Does this speed up your tests? if yes, I'll work on a solution.

**Comment by liqueurdetoile** [comment]
My Mysql server is running on a WSL debian 10 setup located on a not very efficient hard drive and Mysql CREATE/TRUNCATE TABLE statements are quite expensive anyway.

For discussion sake, I've made a little benchmark on different configurations. Times are rounded to nearest integer. Migration is already done. The test by itself is not doing any database interactions. I've run each configuration 3 times to have consistent results.

migrate plugin called | listener settled | test duration (PHPunit)  |  Overall duration | Comment
--|--|---|--|--
no | none  | 1s  |  4s | Cakephp bootstrap time indeed
yes | none  | 1s  |  4s | Nearly no overhead for migration plugin to check all is already migrated
yes | cakephp | 1s | 4s | Nearly no overhead. Not surprising as no fixtures are loaded
yes | cakephp-suite-light (temp dirty table mode) | 20s | 24s | yiiks !
yes | cakephp-suite-light (temp dirty table mode, only disabling cleanAllTables) | 5s | 9s
yes | cakephp-suite-light (temp dirty table mode, disabling cleanAllTables + last call to cleanDirtyTables) | 5s | 9s | no surprise as there's no dirty table
yes | cakephp-suite-light (perm dirty table mode and disabling cleanAllTables) | 1s | 13s

And here's the figure for a test that uses fixtures for 4 models (not even tried to compare with classic fixtures handling that is much slower with 4 fixtures in my experience). 

migrate plugin called | listener settled | test duration (PHPunit)  |  Overall duration | Comment
--|--|---|--|--
yes | cakephp-suite-light (temp dirty table mode) | 22s | 26s
yes | cakephp-suite-light (temp dirty table mode, only disabling cleanAllTables) | 8s | 12s
yes | cakephp-suite-light (temp dirty table mode, disabling cleanAllTables + last call to cleanDirtyTables) | 12s | 16s | Truncating overhead from previous
yes | cakephp-suite-light (perm dirty table mode and disabling cleanAllTables) | 3s | 15s | Similar overall time, Database maintenance is moved out of test scope.

Your suggestion to switch to permanent dirty table is quite handy in my case, especially when using a fixture.

I'm wondering if a way to go should be to use ENV vars to tweak listener behavior as they can easily be settled in PHPUnit configuration, through a wrapper script or even in tests hooks.

For instance :
- `CSL_DISABLE` : true/false (simply skip injector for no fixtures test, useful when looping on one tests)
- `CSL_PERMANENT_DIRTY` : true (use permanent dirty table) / false (temp table)
- `CSL_SKIP_TRUNCATE` : true/false (always skip truncation)
- `CSL_SKIP_TRUNCATE_ONCE` : true/false (skip truncation only for next test, similar to the trait but less verbose)

The CSL_DISABLE with a wrapper script is exactly what I need when looping on a single test that does not manipulate database.

**Comment by pabloelcolombiano** [comment]
Thanks for the in-depth study. Good to read that the performance is back to normal when using a permanent dirty table collector.

I have been working for a solution where the permanent collector is used per default. I'll create a new release for that.

Regarding the additional settings you propose, there are no possibilities to skip the truncation based on the presence of fixtures or not in the test. The present package was initially developed to make the [fixture factories](https://github.com/vierge-noire/cakephp-fixture-factories) possible. In other words, to get rid of the legacy test fixtures. This means that a test without fixtures does not imply that there will be no inserts in the DB.

But I agree that we could parametrize the truncation, either on or off per default, and create a second trait to enable the truncation if it is set to off per default. I suggest you create an issue for this point, and a PR too.

Regarding the permanent or temporary nature of the collector, I propose to have it per default permanent, and provide the possibility to have it temporary in the Datasource parameters of the test DB.

**Comment by liqueurdetoile** [comment]
Thanks for reply. I will work on a PR.

**Comment by pabloelcolombiano** [comment]
I have created the versions v2.1.4 resp. v1.1.4.

I propose to address the configuration part of the discussion in a different issue.

Thanks a lot for the constructive inputs!
