### ISSUE TITLE
Identifier name to long

### ISSUE THREAD

**Issue by maidzen** [vierge-noire/cakephp-test-suite-light#40]
When generating the "dirty_table_spy_*" triggers i get the error 1059 identifier name is to long
this is beacuse mysql is limited to 64 chars and my tablename is already 52 chars long.

Is it possible to shorten the prefix before testing without editing the src ?

**Comment by pabloelcolombiano** [comment]
@maidzen this is something we can work out easily, by reducing the prefix to "dts_*". I'll get that done tonight or tomorrow.

**Comment by pabloelcolombiano** [comment]
@maidzen The latest tag v2.2.1 (v1.2.1 for cake3) should fix your issues. 

Please confirm and feel free to close the issue if that worked.
